apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: nathandougan/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*.js": .
        "**/*.css": .
        "**/*.html": .
    - image: nathandougan/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*js": .
    - image: nathandougan/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "**/*js": .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
